CREATE DATABASE gimep;
USE gimep;

CREATE TABLE user (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tp INTEGER UNSIGNED NOT NULL,
    team INTEGER UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE milestone (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    team INTEGER UNSIGNED NOT NULL,
    reward VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    tp_needed INTEGER UNSIGNED NOT NULL,
    status BOOLEAN NOT NULL
);

CREATE TABLE team (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tp INTEGER UNSIGNED NOT NULL,
    pm INTEGER UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE task(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user INTEGER UNSIGNED,
    status BOOLEAN NOT NULL,
    descript VARCHAR(255)
);